# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "rspec", "~> 3.9"
gem "capybara", "~> 3.33"
gem "sinatra", "~> 2.1"

gem "pg", "~> 1.2"

gem "simplecov", "~> 0.19.0"
gem "simplecov-console", "~> 0.7.2"
